#
# ~/Local/etc/bash/bashrc
#

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias rm='/usr/bin/rm -i'
alias mv='/usr/bin/mv -i'
alias cp='/usr/bin/cp -i'

alias ll='ls -l'
alias la='ls -la'
alias lart='ls -lart'

alias sess='sort | less'

alias open='xdg-open'
alias start='xdg-open'

# EOF
