# -*- coding: utf-8 -*-
# Copyright 2025-2026, Antonio Alvarado <tnotstar@gmail.com>

[starship.variables]
starship_scan_timeout = 50
starship_command_timeout = 350
starship_package_disabled = true
starship_git_branch_disabled = true
starship_git_commit_disabled = true

[tmux.files]
"etc/tmux/tmux.conf" = "~/.tmux.conf"

[linux]
depends = ["tmux"]
