# -*- coding: utf-8 -*-
# Copyright 2025-2026, Antonio Alvarado <tnotstar+copyright@gmail.com>

[starship.variables]
starship_scan_timeout = 50
starship_command_timeout = 400

[tmux.files]
"etc/tmux/tmux.conf" = "~/.tmux.conf"

[linux]
depends = ["tmux"]
