"
" ~/Local/etc/vim/vimrc
"

"""
" common settings
"

if &compatible
    set nocompatible                   " use vim settings, rather than vi ones
endif

" set up encoding and file format
set encoding=utf-8                     " the encoding displayed.
set fileencoding=utf-8                 " the encoding written to file.
set fileformat=unix                    " use `unix` file formats by default

" set up common options
set confirm                            " ask to save changes before next one
set hidden                             " allow hidden buffers when abandon them
set number                             " display line numbers
set ruler                              " show the cursor position all the time
set nowrap                             " by default, disable word wrap
set history=256                        " how many commands of history to recall
set laststatus=2                       " always display status lines
set cmdheight=2                        " set the command window height to 2
set scrolloff=5                        " show a few lines of context around the cursor
set display=truncate                   " show @@@ in the last line, if truncated
set nrformats-=octal                   " don't recognize octal numbers for ^A/^X
set showcmd                            " show incomplete commands in statusline
set showmatch                          " display matching brackets
set wildmenu                           " completion matches in statusline
set cursorline                         " highlight the cursor line
set nomodeline                         " disable modelines for security
set noguipty                           " make external commands work with a pty
set timeout                            " time out on key mappings
set timeoutlen=200                     " key mapping time out on 200ms
set complete-=i                        " disable current & included files scan
set clipboard=unnamedplus              " always use the global clipboard

" set up tabs/spaces options
set autoindent                         " copy indent from current to new line
set expandtab                          " convert tabs to spaces
set backspace=indent,eol,start         " allow backspacing over autoindent,
                                       "   line breaks and start of inserts
set tabstop=4                          " use 4 spaces for tabs
set shiftwidth=4                       " use 4 spaces for indentation
set softtabstop=4                      " backspace key treat 4 spaces as 1 tab

" set up search options
set hlsearch                           " highlight the last used search pattern
if has("reltime")
    set incsearch                      " do incremental searching
endif

" enable file type detection
if has("autocmd")
    filetype plugin indent on          " enable file type, plugins and indent
endif

" switch syntax highlighting on
if has("syntax")
    if !exists("g:syntax_on")
        syntax on
    endif
endif

" set up swap files options
set directory^=$HOME/.vimswap//        " put all swap files together here


"""
" terminal settings
"

if &t_Co > 2
    set t_Co=256                       " try with 256 colors
    colorscheme pablo                  " set default color scheme
endif

" set up terminal options
set visualbell                         " use visual bell instead of beeping
set t_vb=                              " reset the terminal code for visual bell

" set up key remappings
let mapleader="\<Space>"               " first, set leader key up!

nnoremap <Space> <Nop>

nmap <Leader>g :noh<CR>
nmap <Leader>t :NERDTree<CR>
nmap <Leader>w :StripWhitespace<CR>

" ctrl-shift-x is `cut`
vnoremap <C-S-X> "+x

" ctrl-shift-c is `copy`
vnoremap <C-S-C> "+y

" ctrl-shift-v is `paste`
noremap <C-S-V> "+gp

" set up mouse options
if has("mouse")                        " enable mouse mode
  set mouse=a                          " copy&paste with the `shift` key
endif

" EOF vim:ft=vim:tw=78
